version: "3.3"

services:
  mediscreen_ui:
    container_name: ui
    depends_on:
      - mediscreen_info
    build: mediscreenUI/.
    ports:
      - "8080:8080"
    environment:
      - INFO_URL=http://info:8081
    networks:
      mediscreen_net:
        ipv4_address: 172.40.2.1

  mediscreen_info:
    container_name: info
    depends_on:
      - mediscreen_db_sql
    build: mediscreenInfo/.
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.40.2.3:3306/mediscreen
      - SPRING_DATASOURCE_USERNAME=doctor
      - SPRING_DATASOURCE_PASSWORD=rootroot
    networks:
      mediscreen_net:
        ipv4_address: 172.40.2.2

  mediscreen_db_sql:
    container_name: sql
    image:  mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=mediscreen
      - MYSQL_USER=doctor
      - MYSQL_PASSWORD=rootroot
    networks:
      mediscreen_net:
        ipv4_address: 172.40.2.3

networks:
  mediscreen_net:
    ipam:
      config:
        - subnet: 172.40.2.0/14