version: "3.3"

services:
  mediscreen_ui:
    container_name: ui
    depends_on:
      - mediscreen_info
    build: mediscreenUI/.
    ports:
      - "8083:8083"
    environment:
      - INFO_URL=http://info:8081
    networks:
      mediscreen_net:
        ipv4_address: 172.40.2.1

  mediscreen_info:
    container_name: info
    depends_on:
      - mediscreen_db_sql
    build: mediscreenInfo/.
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://sql:3306/mediscreen?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_PASSWORD=rootroot
      - SPRING_DATASOURCE_USERNAME=root
    networks:
      mediscreen_net:
        ipv4_address: 172.40.2.2

  mediscreen_db_sql:
    container_name: sql
    image:  'mysql:8.0'
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=mediscreen
      - MYSQL_PASSWORD=rootroot
    ports:
      - "3307:3306"
    networks:
      mediscreen_net:
        ipv4_address: 172.40.2.3

networks:
  mediscreen_net:
    ipam:
      config:
        - subnet: 172.40.2.0/14