version: "3.3"

services:
  mediscreen_ui:
    container_name: ui
    depends_on:
      - mediscreen_info
      - mediscreen_note
      - mediscreen_assess
    build: mediscreenUI/.
    ports:
      - "8083:8083"
    environment:
      - INFO_URL=http://info:8081
      - NOTE_URL=http://note:8082
      - ASSESS_URL=http://assess:8080
    networks:
      mediscreen_net:
        ipv4_address: 172.40.2.1

  mediscreen_info:
    container_name: info
    depends_on:
      - mediscreen_db_sql
    build: mediscreenInfo/.
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://sql:3306/mediscreen?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_PASSWORD=rootroot
      - SPRING_DATASOURCE_USERNAME=root
    networks:
      mediscreen_net:
        ipv4_address: 172.40.2.2

  mediscreen_db_sql:
    container_name: sql
    image:  'mysql:8.0'
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=mediscreen
      - MYSQL_PASSWORD=rootroot
    ports:
      - "3307:3306"
    networks:
      mediscreen_net:
        ipv4_address: 172.40.2.3

  mediscreen_note:
    container_name: note
    depends_on:
      - mediscreen_db_mongodb
    build: mediscreenNote/.
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE=admin
      - SPRING_DATA_MONGODB_DATABASE=mediscreen
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_HOST=mongodb
    networks:
      mediscreen_net:
        ipv4_address: 172.40.2.4

  mediscreen_db_mongodb:
    container_name: mongodb
    image: 'mongo:5.0'
    environment:
      - MONGO_INITDB_DATABASE=mediscreen
    ports:
      - "27018:27017"
    networks:
      mediscreen_net:
        ipv4_address: 172.40.2.5

  mediscreen_assess:
    container_name: assess
    depends_on:
      - mediscreen_info
      - mediscreen_note
    build: mediscreenCalcul/.
    ports:
      - "8080:8080"
    environment:
      - INFO_URL=http://info:8081
      - NOTE_URL=http://note:8082
    networks:
      mediscreen_net:
        ipv4_address: 172.40.2.6


networks:
  mediscreen_net:
    ipam:
      config:
        - subnet: 172.40.2.0/14